### ISSUE TITLE
Add Lesson Plans in Topic Detail page

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#11]
Show the lesson plans on the topic detail page in a layout similar to the testimonials (on the home page) i.e. in an infinite slider. The lesson plan name, aim and a view more button should be contained in a card, similar to the dashboard. 

**Steps for viewing topic detail page**
- Create topic(s)
- Create lesson plan and assign the topic(s) to lesson plans
- Go to the dashboard (Steps for accessing dashboard: #3)
- Select the topic name to view a topic detail page.

**Comment by shubhammehra4** [comment]
May I take this up?

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/118393425-b67fb000-b65c-11eb-956b-b3d892358629.png)
Is this ok?

**Comment by shubhammehra4** [comment]
Do I hide the aim in mobile view?

**Comment by avgupt** [comment]
Seems good. If you think including aim is crowding the UI, you may commit aim.

**Comment by shubhammehra4** [comment]
For now, the aim is visible in the mobile UI. This page seems a little empty in desktop view so you might consider adding some more information about the topic itself and also pointing to its parent topic if any.

Side Note:- as this is an infinite slider if a topic has less than 3 lesson plans associated with it, the same lesson plan is visible more than once in the desktop view which can affect the user experience.

**Comment by avgupt** [comment]
@shubhammehra4, thanks for the suggestions; I will look into it. I appreciate your concern for the infinite slider, but there would be a considerable number of lesson plans in production.
