### ISSUE TITLE
View Dashboard Button when User is Signed In

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#17]
Once the user is signed in, the navigation bar should also include a Dashboard tab. On clicking the Dashboard tab, the user should be directed to the dashboard.

(Steps for accessing dashboard: #3)

**Comment by shubhammehra4** [comment]
May I take this up?

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/120107158-89afba80-c17d-11eb-9a23-84f55e2992fc.png)
ok?

**Comment by avgupt** [comment]
Looks good! @shubhammehra4
