### ISSUE TITLE
View Topic(s) on lesson plan detail page

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#18]
Show the topic(s) of the lesson plan below the plan title on the lesson plan detail page.

(Steps for viewing lesson plans: #3)

**Comment by shubhammehra4** [comment]
May I take this up?

**Comment by avgupt** [comment]
Sure, go ahead.

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/119265047-f289b680-bc02-11eb-8c3a-f1872b5d17c8.png)
I'm displaying them like badges, is this ok?
Any other style changes?

**Comment by avgupt** [comment]
Looks good!
