### ISSUE TITLE
Improve the Logout Page design

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#2]
Redesign the [logout](http://127.0.0.1:8000/accounts/logout/) page to align the text on the center of the page and extend the navigation bar.

**Comment by shubhammehra4** [comment]
Can I Take this issue?

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/117582892-e3463b80-b121-11eb-99c1-4a4940d4c678.png)
Please refer to the photo and confirm if this is okay?

**Comment by avgupt** [comment]
> ![image](https://user-images.githubusercontent.com/54092258/117582892-e3463b80-b121-11eb-99c1-4a4940d4c678.png)
> Please refer to the photo and confirm if this is okay?

Looks great! Could you align the text vertically too?

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/117583531-379eea80-b125-11eb-9a04-e601017011ba.png)
Any styling changes ?

**Comment by avgupt** [comment]
> ![image](https://user-images.githubusercontent.com/54092258/117583531-379eea80-b125-11eb-9a04-e601017011ba.png)
> Any styling changes ?

Seems good!

**Comment by avgupt** [comment]
Resolved with #7
