### ISSUE TITLE
View Lesson Plans According to Topics On Dashboard

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#3]
### Steps for creating a dashboard for a user
- Create a [superuser](https://docs.djangoproject.com/en/1.8/intro/tutorial02/)
- Go to [admin page](http://127.0.0.1:8000/admin/)
- Create a user and some dummy lesson plans
- Assign the lesson plan to the created user
- Logout and [Sign In](http://127.0.0.1:8000/accounts/login/) using the created user's credentials

Use [cards](https://getbootstrap.com/docs/5.0/components/card/) for the lesson plans and show them under different headings -  according to the topic name. If a lesson plan has more than one topic, show the lesson plan in each topic category.

**Comment by shubhammehra4** [comment]
Can I take this up?

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/117676027-c87bd180-b1ca-11eb-8920-904295108e8e.png)
![image](https://user-images.githubusercontent.com/54092258/117676070-d6c9ed80-b1ca-11eb-830e-a8bcb1a9644e.png)
is the layout ok ?
Do mention styling changes and if any other fields should be displayed in the plan card.

**Comment by avgupt** [comment]
@shubhammehra4 Instead of blue buttons, you may choose the color of the navigation bar. In the mobile view, the text "Welcome To Your Dashboard" is not following margins (#4).
Drop the aim for mobile view. Reduce the card width for mobile - two cards can be shown in one row.

**Comment by shubhammehra4** [comment]
![image](https://user-images.githubusercontent.com/54092258/117764225-c60c8c80-b249-11eb-9167-81f423059952.png)
![image](https://user-images.githubusercontent.com/54092258/117764241-cc9b0400-b249-11eb-8042-1108f53515ba.png)
is this alright?

**Comment by shubhammehra4** [comment]
Side Note:- Consider changing ```  python makemigrations``` to ``` python manager.py makemigrations``` in the readme as the first one didn't seem to work.

**Comment by avgupt** [comment]
> Side Note:- Consider changing ` python makemigrations` to ` python manager.py makemigrations` in the readme as the first one didn't seem to work.

Thanks for pointing that out! I'll fix it.

**Comment by avgupt** [comment]
@shubhammehra4 Seems like "Welcome to your dashboard" and the topic names are not vertically aligned in the desktop view. It's a low-priority issue you can take up in the future.

**Comment by shubhammehra4** [comment]
I fixed the alignment issue in the PR.
Also, a user can visit the login page(if he enters the route manually) even when he is signed in this might result in some unexpected behavior😅

**Comment by avgupt** [comment]
> I fixed the alignment issue in the PR.
> Also, a user can visit the login page(if he enters the route manually) even when he is signed in this might result in some unexpected behavior

Please mention the issue in your PR.
I'll work on the issue. Thanks :)
