### ISSUE TITLE
Add Option for Feedback in website

### ISSUE THREAD

**Issue by avgupt** [Leesha-Noble-Souls/ParentTrainingApp#8]
This issue has the following tasks:

- [ ] Create a model for feedback.
- [ ] Add input box for feedback on each lesson plan.
- [ ] Show feedbacks to admin.
- [ ] Provide notifications for new feedback to admin.

**Comment by ayushi19031** [comment]
I would like to work on this issue
For to create a model

**Comment by ayushi19031** [comment]
I will take the issue

**Comment by avgupt** [comment]
Partially completed in #20

**Comment by avgupt** [comment]
Code in #20 was broken. Reverted the changes.
